### ISSUE TITLE
Stepper exposes internal error "supposed to be skipped"

### ISSUE THREAD

**Issue by LiberalArtist** [racket/htdp#46] opened 2017-11-11 19:48 UTC
I am helping a friend who is working through HtDP 2e, and his (incomplete and still buggy) attempt to work through [3.6 Designing World Programs](http://www.ccs.neu.edu/home/matthias/HtDP2e/part_one.html#%28part._.D.K._sec~3adesign-world%29) is exposing an internal error in the Stepper.

Given the following program in `Beginning Student` language (i.e. no `#lang`):
```racket
(require 2htdp/image)
(require 2htdp/universe)

(define CAR-FINAL
  ; I have replaced the car with a rectangle for simplicity
  (rectangle 30 15 'solid 'black))

(define BACKGROUND
  (rectangle (* 8 (image-width CAR-FINAL))
             (* 2 (image-height CAR-FINAL))
             "outline"
             "black"))

(define Y-CAR
  (- (image-height BACKGROUND)
     (* .5 (image-height CAR-FINAL))))

(define (render ws)
  (place-image CAR-FINAL ws Y-CAR BACKGROUND))

(define (tock ws)
  (+ 3 ws))

(check-expect (tock 20) 23)
(check-expect (tock 78) 81)


(define (end? ws)
  (= ws (+ (image-width BACKGROUND)
           (* .5 (image-width CAR-FINAL)))))

(define (main ws)
  (big-bang ws
    [on-tick tock]
    [to-draw render]
    [stop-when end?]))

(main 5)
```
running the Stepper produces the following error message on the right-hand side in step 15/19:
```
skip-step?: contract violation
  expected: (or/c (listof procedure?) #f)
  given: (cons (lambda () ...) (cons "supposed to be skipped" (cons (lambda () ...) '())))
  in: the 2nd argument of
      (->
       (or/c
        'normal-break
        'normal-break/values
        'result-exp-break
        'result-value-break
        'double-break
        'late-let-break
        'expr-finished-break
        'define-struct-break)
       (or/c (listof procedure?) #f)
       render-settings?
       boolean?)
  contract from: 
      <pkgs>/htdp-lib/stepper/private/reconstruct.rkt
  blaming: <pkgs>/htdp-lib/stepper/private/model.rkt
   (assuming the contract is correct)
  at: <pkgs>/htdp-lib/stepper/private/reconstruct.rkt:48.2
```

**Comment by jbclements** [comment] 2019-07-09 07:58
Duplicate of #69 ...

**Closed by jbclements** 2019-07-09 07:58 UTC
Labels: stepper
